### ISSUE TITLE
Cannot visit profiles after upgrading to PHP7.

### ISSUE THREAD

**Issue by Kitty1789** [noxwyll/Steam-Login-MyBB-1.8#46]
Hey, I upgraded to PHP7 today, so far the forum itself works fine, the only thing that fucks up is if I try to visit a profile, then steamlogin errors (I even freshly updated it today).

Code:

`2017/04/14 00:27:58 [error] 31606#0: *196 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function bcsub() in /var/www/wtcweb/main/inc/class_steam.php:102
Stack trace:
#0 /var/www/wtcweb/main/inc/plugins/steamlogin.php(522): steam->convert64to32('765611981442975...')
#1 /var/www/wtcweb/main/inc/class_plugins.php(139): steamify_user_profile('')
#2 /var/www/wtcweb/main/member.php(1944): pluginSystem->run_hooks(Array)
#3 {main}
  thrown in /var/www/wtcweb/main/inc/class_steam.php on line 102" while reading response header from upstream, client: CENSORED IP, server: wtcghostcommunity.com, request: "GET /member.php?action=profile&uid=163 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "wtcghostcommunity.com", referrer: "https://wtcghostcommunity.com/"`

**Comment by Kitty1789** [comment]
Was an issue with php7 not installing the default packages, sorry.
